extends: 'eslint:recommended'
env:
  es6: true
rules:
  accessor-pairs: 2
  array-bracket-spacing:
    - 2
    - always
  array-callback-return: 2
  arrow-body-style:
    - 2
    - as-needed
  arrow-parens:
    - 2
    - always
  arrow-spacing:
    - 2
    - after: true
      before: true
  block-scoped-var: 2
  block-spacing: 2
  brace-style:
    - 1
    - 1tbs
    - allowSingleLine: true
  callback-return: 2
  camelcase: 0
  comma-spacing:
    - 2
    - after: true
      before: false
  comma-style:
    - 2
    - first
  complexity:
    - 2
    - 20
  computed-property-spacing:
    - 2
    - never
  consistent-return: 0
  consistent-this: 2
  curly:
    - 1
    - multi-or-nest
    - consistent
  default-case: 2
  dot-location:
    - 2
    - property
  dot-notation: 1
  eol-last: 2
  eqeqeq: 2
  func-names: 0
  func-style:
    - 2
    - declaration
    - allowArrowFunctions: true
  generator-star-spacing: 2
  global-require: 2
  guard-for-in: 2
  handle-callback-err: 2
  id-blacklist: 2
  id-length:
    - 2
    - exceptions:
      - $
  id-match: 2
  indent: 0
  init-declarations: 0
  jsx-quotes: 2
  key-spacing: 1
  keyword-spacing:
    - 2
    - after: true
      before: true
  linebreak-style:
    - 2
    - unix
  lines-around-comment: 0
  max-depth: 2
  max-len: 
    - 2
    - code: 80
      comments: 100
      ignoreTrailingComments: true
      ignoreUrls: true

  max-nested-callbacks: 2
  max-params: 0
  max-statements:
    - 1
    - 50
  new-cap: 2
  new-parens: 2
  newline-after-var: 0
  newline-per-chained-call: 0
  no-alert: 0
  no-array-constructor: 2
  no-bitwise: 0
  no-caller: 2
  no-case-declarations: 1
  no-catch-shadow: 0
  no-confusing-arrow: 2
  no-continue: 0
  no-div-regex: 2
  no-else-return: 0
  no-empty-function: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-extra-parens:
    - 2
    - functions
  no-floating-decimal: 2
  no-implicit-coercion:
    - 2
    - boolean: false
  no-implicit-globals: 2
  no-implied-eval: 2
  no-inline-comments: 0
  no-invalid-this: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 1
  no-loop-func: 2
  no-magic-numbers: 0
  no-mixed-requires: 2
  no-mixed-spaces-and-tabs: 2
  no-multi-spaces: 1
  no-multi-str: 2
  no-multiple-empty-lines: 2
  no-native-reassign: 2
  no-negated-condition: 0
  no-nested-ternary: 1
  no-new: 2
  no-new-func: 2
  no-new-object: 2
  no-new-require: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-param-reassign: 0
  no-path-concat: 2
  no-plusplus: 0
  no-process-env: 2
  no-process-exit: 0
  no-proto: 2
  no-restricted-imports: 2
  no-restricted-modules: 2
  no-restricted-syntax: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-shadow:
    - 2
    - builtinGlobals: true
      allow:
      - err
      - event # env browser has this as global
  no-shadow-restricted-names: 2
  no-spaced-func: 2
  no-sync: 2
  no-ternary: 0
  no-throw-literal: 2
  no-trailing-spaces: 2
  no-undef-init: 2
  no-undefined: 0
  no-underscore-dangle:
    - 2
    - allow:
        - _read
        - _write
        - _transform
        - _flush
        - _id
  no-unmodified-loop-condition: 0
  no-unneeded-ternary: 2
  no-unused-expressions: 2
  no-use-before-define: 0
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-constructor: 2
  no-var: 2
  no-void: 2
  no-warning-comments: 1
  no-whitespace-before-property: 2
  no-with: 2
  object-curly-spacing:
    - 2
    - always
  object-shorthand: 0
  one-var:
    - 2
    - never
  one-var-declaration-per-line: 2
  operator-assignment:
    - 2
    - always
  operator-linebreak:
    - 2
    - after
  padded-blocks: 0
  prefer-arrow-callback: 1
  prefer-const: 2
  prefer-reflect: 0
  prefer-rest-params: 0
  prefer-spread: 2
  prefer-template: 0
  quote-props:
    - 1
    -  consistent
  quotes:
    - 2
    - single
  radix: 2
  require-jsdoc: 0
  require-yield: 2
  semi:
    - 2
    - never
  semi-spacing: 2
  sort-imports: 2
  sort-vars: 0
  space-before-blocks: 2
  space-before-function-paren:
    - 2
    - never
  space-in-parens:
    - 1
    - never
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment:
    - 2
    - always
  strict: 2
  template-curly-spacing: 2
  valid-jsdoc: 2
  vars-on-top: 2
  wrap-iife: 2
  wrap-regex: 0
  yield-star-spacing: 2
  yoda:
    - 2
    - never
